info:
  name: delete_address
  type: http
  seq: 5

http:
  method: DELETE
  url: http://{{host}}:{{port}}/api/setup/warehouse/address
  body:
    type: json
    data: ""

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
