info:
  name: get RR Details
  type: http
  seq: 4

http:
  method: GET
  url: http://{{host}}:{{port}}/api/setup/report2/purchase_order/20
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
