info:
  name: update_area
  type: http
  seq: 4

http:
  method: PUT
  url: http://{{host}}:{{port}}/api/setup/warehouse/area
  body:
    type: json
    data: "{\r

      \    \"id\":   2,\r

      \    \"code\": \"gen 0001\",\r

      \    \"name\": \"General\"\r

      }"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
